dependencies {
    implementation project(':model')
    implementation 'org.springframework:spring-context'

    // R2DBC + MySQL
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'io.asyncer:r2dbc-mysql:1.3.2'
    implementation 'io.r2dbc:r2dbc-pool'

    // Flyway + JDBC driver MySQL
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-mysql'   // <-- agrega esto
    runtimeOnly 'com.mysql:mysql-connector-j'

    // (Opcional) utilidades scaffold
    implementation 'org.reactivecommons.utils:object-mapper-api:0.1.0'
    testImplementation 'org.reactivecommons.utils:object-mapper:0.1.0'

    // Lombok (necesario por @Data / @RequiredArgsConstructor)
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
}
